name: 'Pull request branch updater'
description: 'GitHub Action to update pull request with base branches'
inputs:
  token:
    description: 'token to be used for making authenticated calls to the GitHub API'
    required: false
    default: ${{ github.token }}
  repo:
    description: 'the repo where you want to update the pull requests, defaults to the current repository executing the runner'
    required: false
    default: ${{ github.repository }}
runs:
  using: 'node16'
  main: 'dist/index.js'